[package]
name = "Publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
uuid = { version = "1.3", features = ["v4"] }
